config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  namespace :courier_admin do
    root 'index#index'
    resources :legal_entities
    resources :courier_services
    resources :couriers
    resources :orders do
      member do
        get :cancel
        get :courier
      end
    end
  end

  namespace :shop_admin do
    root 'index#index'
    
    devise_for :shop_users

    scope :profile do
      root 'profile#show', as: :profile
      resource :legal_entity, controller: :legal_entity, only: [:edit, :update]
      resources :stores
      resources :shops do
        resources :shop_delivery_values, except: [:index]
      end
    end

    scope :settings do
      root 'account_settings#edit', as: :settings
      resource :account_settings, only: [:update]
    end

    resources :notifications, only: [:index, :destroy]
    resources :reports, only: [:index]
    
    resources :orders, except: [:destroy] do
      resources :order_items, except: [:index, :show]
      member do
        get :publish
        get :confirm
        get :cancel
        get :courier
      end
    end

    resource :documents, only: [] do
      get :transmission_reception
      get :transmission_return
      get :cancel
      get :agent
    end
  end

  scope :courier_admin do
    devise_for :courier_users
  end

  namespace :gp_core do
    namespace :api do
      namespace :v1 do
        resources :orders
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :shop_user
  belongs_to :store
  belongs_to :shop

  STATUSES = {
      unpublished: 0,
      published: 1,
      confirmed: 2,
      assigned: 3,
      courier_canceled: 4,
      shop_canceled: 5,
      courier: 6,
      courier_returned: 7,
      shop_returned: 8,
      delivered: 9,
      returned: 10
    }

  PAYMENT_TYPES = %w(other cash card)

  RETURN_REASONS = %w(rejected_by_customer courier_failed)
  RETURN_METHODS = %w(direct_to_shop through_courier_store)

  validates :status_id,
    {
      numericality: {
          only_integer: true,
          greater_than: -1,
          less_than: 11
        }
    }
  
  def has_status?(status_name)
    return false unless STATUSES.has_key? status_name
    return false unless status_id == STATUSES[status_name]
    true 
  end

  def update_status(status_name, attributes = {})
    if update_attributes(attributes.merge(status_id: STATUSES[status_name]))
      shop_user.notifications.create({
          subject: I18n.t('notifications.subject.order_status_changed', id: id),
          message: I18n.t("notifications.body.status_changed_to_#{status_name}", id: id)
        })
      true
    else
      false
    end
  end

  def status_options_list
    STATUSES.each_pair{ |k, v| [I18n.t("order.status.#{k}"), v] }
  end

  def payment_types_options_list
    PAYMENT_TYPES.map{ |v| [I18n.t("order.payment_type.#{v}"), v] }
  end

  def status_name
    I18n.t("order.status.#{STATUSES.to_a[status_id].first}")
  end

  def payment_type_name
    I18n.t("order.payment_type.#{payment_type}")
  end
end

app/controllers/courier_admin/application_controller.rb
module CourierAdmin
  class ApplicationController < ActionController::Base
    before_action :authenticate_courier_user!
    protect_from_forgery with: :exception
    layout 'courier_admin'
  end
end

app/controllers/courier_admin/courier_services_controller.rb
module CourierAdmin
  class CourierServicesController < CourierAdmin::ApplicationController
    before_action :set_courier_admin_courier_service, only: [:show, :edit, :update, :destroy]

    # GET /courier_admin/courier_services
    def index
      @courier_services = current_courier_user.courier_services.all
    end

    # GET /courier_admin/courier_services/1
    def show
    end

    # GET /courier_admin/courier_services/new
    def new
      @courier_service = CourierService.new
    end

    # GET /courier_admin/courier_services/1/edit
    def edit
    end

    # POST /courier_admin/courier_services
    def create
      @courier_service = current_courier_user.courier_services.new(courier_service_params)

      if @courier_service.save
        redirect_to [:courier_admin, @courier_service], notice: 'Courier service was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /courier_admin/courier_services/1
    def update
      if @courier_service.update(courier_service_params)
        redirect_to [:courier_admin, @courier_service], notice: 'Courier service was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /courier_admin/courier_services/1
    def destroy
      @courier_service.destroy
      redirect_to courier_admin_courier_services_url, notice: 'Courier service was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_courier_admin_courier_service
        @courier_service =  current_courier_user.courier_services.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def courier_service_params
        params.require(:courier_service).permit(:title, :contact_name,
          :address, :store_address, :store_contact_name, :phone,
          :store_phone, :email)
      end
  end
end

app/controllers/courier_admin/couriers_controller.rb
module CourierAdmin
  class CouriersController < CourierAdmin::ApplicationController
    before_action :set_courier_admin_courier, only: [:show, :edit, :update, :destroy]

    # GET /courier_admin/couriers
    def index
      @couriers = current_courier_user.couriers.all
    end

    # GET /courier_admin/couriers/1
    def show
    end

    # GET /courier_admin/couriers/new
    def new
      @courier = Courier.new
    end

    # GET /courier_admin/couriers/1/edit
    def edit
    end

    # POST /courier_admin/couriers
    def create
      @courier = current_courier_user.couriers.new(courier_params)

      if @courier.save
        redirect_to [:courier_admin, @courier], notice: 'Courier was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /courier_admin/couriers/1
    def update
      if @courier.update(courier_admin_courier_params)
        redirect_to [:courier_admin, @courier], notice: 'Courier was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /courier_admin/couriers/1
    def destroy
      @courier.destroy
      redirect_to courier_admin_couriers_url, notice: 'Courier was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_courier_admin_courier
        @courier = current_courier_user.couriers.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def courier_params
        params.require(:courier)
          .permit(:name, :status_id, :passport, :transport_type, :phone,
            :payments, :string, :orders_type)
      end
  end
end

app/controllers/courier_admin/index_controller.rb
module CourierAdmin 
  class IndexController < CourierAdmin::ApplicationController
    def index
    end
  end
end

app/controllers/courier_admin/legal_entities_controller.rb
module CourierAdmin
  class LegalEntitiesController < CourierAdmin::ApplicationController
    before_action :set_legal_entity, only: [:show, :edit, :update, :destroy]

    # GET /legal_entities
    def index
      @legal_entities = current_courier_user.legal_entities.all
    end

    # GET /legal_entities/1
    def show
    end

    # GET /legal_entities/new
    def new
      @legal_entity = LegalEntity.new
    end

    # GET /legal_entities/1/edit
    def edit
    end

    # POST /legal_entities
    def create
      @legal_entity = current_courier_user.legal_entities.build(legal_entity_params)

      if @legal_entity.save
        redirect_to [:courier_admin, @legal_entity], notice: 'Legal entity was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /legal_entities/1
    def update
      if @legal_entity.update(legal_entity_params)
        redirect_to [:courier_admin, @legal_entity], notice: 'Legal entity was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /legal_entities/1
    def destroy
      @legal_entity.destroy
      redirect_to courier_admin_legal_entities_url, notice: 'Legal entity was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_legal_entity
        @legal_entity = current_courier_user.legal_entities.find(params[:id])
      end

      def legal_entity_params 
        params.require(:legal_entity).permit(:title, :legal_address, :physical_address,
          :ogrn, :inn, :kpp, :okved, :okpo, :bik, :bank_name,
          :correspondent_account,:checking_account, :general_manager,
          :general_accountant, :contact_phone, :contact_email)
      end
  end
end

app/controllers/courier_admin/orders_controller.rb
module CourierAdmin
  class OrdersController < CourierAdmin::ApplicationController
    before_action :set_order, except: [:index, :new, :create]

    # GET /orders
    def index
      @orders = current_courier_user.orders.all
    end

    # GET /orders/1
    def show
    end

    # GET /orders/new
    def new
      @order = Order.new
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    def create
      @order = current_courier_user.orders.build(order_params)

      if @order.save
        redirect_to [:courier_admin, @order], notice: 'Order was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /orders/1
    def update
      if @order.update(order_params)
        redirect_to [:courier_admin, @order], notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /orders/1
    def destroy
      @order.destroy
      redirect_to courier_admin_orders_url, notice: 'Order was successfully destroyed.'
    end

    def courier
      if OrderStatusManager.new(@order).transfer_to_courier
        flash[:notice] = 'Order was successfully transfered to courier.'
      end
      redirect_to [:courier_admin, @order]
    end

    def cancel
      if OrderStatusManager.new(@order).cancel_by_courier
        flash[:notice] = 'Order was successfully canceled.'
      end
      redirect_to [:courier_admin, @order]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = Order.where(id: params[:id],
          courier_user_id: current_courier_user.id).first
      end

      def order_params
        
        params.require(:order).permit(:status_id, :courier_user_id, :shop_id,
          :shop_order_id, :store_id, :store_address, :courier_order_id,
          :courier_id, :courier_order_id, :status_id, :client_name, :client_phone,
          :client_second_phone, :client_email, :address, :floor, :intercom_code,
          :goods_title, :goods_count, :goods_weight, :goods_estimated_value,
          :goods_value, :delivery_value, :goods_estimated_value, :payment_type,
          :comments)
      end
  end
end

app/controllers/gp_core/api/v1/orders_controller.rb
module GpCore
  module Api
    module V1
      class OrdersController < ApiApplicationController
        def create
          order = Order.create(published_order_params)
          respond_with(order)
        end

        private
          def published_order_params
            params[:order].merge!(status_id: 0,
              delivery_value: 500,
              goods_estimated_value: 1000)
            
            params.require(:order).permit(:shop_user_id, :shop_id, :shop_order_id, :store_id,
              :store_address, :courier_order_id, :courier_id, :courier_order_id,
              :status_id, :client_name, :client_phone, :client_second_phone,
              :client_email, :address, :floor, :intercom_code, :goods_title,
              :goods_count, :goods_weight, :goods_estimated_value, :goods_value,
              :payment_type, :comments)
          end
      end
    end
  end
end

app/controllers/shop_admin/orders_controller.rb
module ShopAdmin
  class OrdersController < ShopAdmin::ApplicationController
    before_action :set_order, except: [:index, :new, :create]

    # GET /orders
    def index
      @q = current_user.orders.search(params[:q])
      @orders = @q.result
    end

    # GET /orders/1
    def show
    end

    # GET /orders/new
    def new
      @order = Order.new
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    def create
      @order = current_user.orders.build(order_params)
      if @order.save
        redirect_to [:shop_admin, @order], notice: 'Order was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /orders/1
    def update
      if @order.update(order_params)
        redirect_to [:shop_admin, @order], notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    def publish
      if OrderStatusManager.new(@order).publish
        flash[:notice] = 'Order was successfully published.'
      end
      redirect_to [:shop_admin, @order]
    end

    def confirm
      if OrderStatusManager.new(@order).confirm
        flash[:notice] = 'Order was successfully confirmed.'
      end
      redirect_to [:shop_admin, @order]
    end

    def cancel
      if OrderStatusManager.new(@order).cancel_by_shop
        flash[:notice] = 'Order was successfully canceled.'
      end
      redirect_to [:shop_admin, @order]
    end

    def courier
      if OrderStatusManager.new(@order).transfer_to_courier
        flash[:notice] = 'Order was successfully transfered to courier.'
      end
      redirect_to [:shop_admin, @order]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = current_user.orders.find(params[:id])
      end

      def order_params
        store = current_user.stores.find(params[:order][:store_id])

        params.require(:order).permit(:shop_user_id, :shop_title,
          :shop_order_id, :shop_price, :store_id, :store_address, :store_address_info,
          :courier_order_id,:courier_id, :courier_order_id, :status_id,
          :customer_name, :customer_phone, :customer_second_phone, :customer_email,
          :delivery_address, :goods_estimated_price, :goods_price, :intercom_code, :payment_type, :comments).merge({
            shop_user_id: current_user.id,
            shop_id: store.shop.id,
            shop_title: store.shop.title,
            shop_price: store.shop.calculate_compensation(params[:order][:goods_price]),
            store_address: store.address,
            store_address_info: store.address_info
          })
      end

      def search_params
        params.require(:order).permit(:shop_id, :shop_order_id, :created_at, :status_id, :store_id)
      end
  end
end

app/helpers/courier_admin/courier_services_helper.rb
module CourierAdmin::CourierServicesHelper
end

app/helpers/courier_admin/couriers_helper.rb
module CourierAdmin::CouriersHelper
end

app/helpers/courier_admin/index_helper.rb
module CourierAdmin::IndexHelper
end

app/views/courier_admin/orders/_form.html.slim
= simple_form_for [:courier_admin, @order], :html => { :class => "form-horizontal" } do |f|

  = f.input :store_address
  = error_span(@order[:store_address])
  = f.input :courier_id
  = error_span(@order[:courier_id])
  = f.input :courier_order_id
  = error_span(@order[:courier_order_id])
  = f.input :status_id
  = error_span(@order[:status_id])
  = f.input :client_name
  = error_span(@order[:client_name])
  = f.input :client_phone
  = error_span(@order[:client_phone])
  = f.input :client_second_phone
  = error_span(@order[:client_second_phone])
  = f.input :client_email
  = error_span(@order[:client_email])
  = f.input :address
  = error_span(@order[:address])
  = f.input :floor
  = error_span(@order[:floor])
  = f.input :intercom_code
  = error_span(@order[:intercom_code])
  = f.input :goods_estimated_value
  = error_span(@order[:goods_estimated_value])
  = f.input :goods_value
  = error_span(@order[:goods_value])
  = f.input :delivery_value
  = error_span(@order[:delivery_value])
  = f.input :payment_type
  = error_span(@order[:payment_type])
  = f.input :comments
  = error_span(@order[:comments])
  = f.button :submit, :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), courier_admin_orders_path, :class => 'btn btn-default'

app/views/courier_admin/orders/_order_items.html.slim
h1 Listing order_items

table class="table table-striped"
  thead
    tr
      th Shop good
      th Weight
      th Width
      th Height
      th Thickness
      th Price
      th Count

  tbody
    - order.order_items.each do |order_item|
      tr
        td = order_item.shop_good_id
        td = order_item.weight
        td = order_item.width
        td = order_item.height
        td = order_item.thickness
        td = order_item.price
        td = order_item.count

app/views/courier_admin/orders/edit.html.slim
- model_class = Order
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courier_admin/orders/index.html.slim
- model_class = Order
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:shop_title)
      th= model_class.human_attribute_name(:store_address)
      th= model_class.human_attribute_name(:courier_id)
      th= model_class.human_attribute_name(:courier_order_id)
      th= model_class.human_attribute_name(:status_id)
      th= model_class.human_attribute_name(:client_name)
      th= model_class.human_attribute_name(:client_phone)
      th= model_class.human_attribute_name(:address)
      th= model_class.human_attribute_name(:goods_value)
      th= model_class.human_attribute_name(:delivery_value)
      th= model_class.human_attribute_name(:payment_type)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @orders.each do |order|
      tr
        td= link_to order.id, courier_admin_order_path(order)
        td= order.shop_title
        td= order.store_address
        td= order.courier_id
        td= order.courier_order_id
        td= order.status_id
        td= order.client_name
        td= order.client_phone
        td= order.address
        td= order.goods_value
        td= order.delivery_value
        td= order.payment_type
        td=l order.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_courier_admin_order_path(order), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), courier_admin_order_path(order), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_courier_admin_order_path, :class => 'btn btn-primary'

app/views/courier_admin/orders/new.html.slim
- model_class = Order
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courier_admin/orders/show.html.slim
- model_class = Order
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:shop_user_id) + ':'
  br
  = @order.shop_user_id
p
  strong= model_class.human_attribute_name(:shop_id) + ':'
  br
  = @order.shop_id
p
  strong= model_class.human_attribute_name(:shop_order_id) + ':'
  br
  = @order.shop_order_id
p
  strong= model_class.human_attribute_name(:shop_title) + ':'
  br
  = @order.shop_title
p
  strong= model_class.human_attribute_name(:store_id) + ':'
  br
  = @order.store_id
p
  strong= model_class.human_attribute_name(:store_address) + ':'
  br
  = @order.store_address
p
  strong= model_class.human_attribute_name(:courier_user_id) + ':'
  br
  = @order.courier_user_id
p
  strong= model_class.human_attribute_name(:courier_id) + ':'
  br
  = @order.courier_id
p
  strong= model_class.human_attribute_name(:courier_order_id) + ':'
  br
  = @order.courier_order_id
p
  strong= model_class.human_attribute_name(:status_id) + ':'
  br
  = @order.status_id
p
  strong= model_class.human_attribute_name(:client_name) + ':'
  br
  = @order.client_name
p
  strong= model_class.human_attribute_name(:client_phone) + ':'
  br
  = @order.client_phone
p
  strong= model_class.human_attribute_name(:client_second_phone) + ':'
  br
  = @order.client_second_phone
p
  strong= model_class.human_attribute_name(:client_email) + ':'
  br
  = @order.client_email
p
  strong= model_class.human_attribute_name(:address) + ':'
  br
  = @order.address
p
  strong= model_class.human_attribute_name(:floor) + ':'
  br
  = @order.floor
p
  strong= model_class.human_attribute_name(:intercom_code) + ':'
  br
  = @order.intercom_code
p
  strong= model_class.human_attribute_name(:goods_value) + ':'
  br
  = @order.goods_value
p
  strong= model_class.human_attribute_name(:delivery_value) + ':'
  br
  = @order.delivery_value
p
  strong= model_class.human_attribute_name(:payment_type) + ':'
  br
  = @order.payment_type
p
  strong= model_class.human_attribute_name(:comments) + ':'
  br
  = @order.comments

- if @order.status_id < 3
  = link_to t('order.cancel'), cancel_courier_admin_order_path(@order), :class => 'btn btn-default'

- if @order.status_id == 3
  = link_to t('order.courier'), courier_shop_admin_order_path(@order), :class => 'btn btn-default'

= link_to t('.back', :default => t("helpers.links.back")), courier_admin_orders_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_courier_admin_order_path(@order), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), courier_admin_order_path(@order), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

= render partial: 'order_items', locals: { order: @order }