config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  namespace :courier_admin do
    root 'index#index'
    resources :legal_entities
    resources :courier_services
    resources :couriers
    resources :orders do
      member do
        get :cancel
        get :courier
      end
    end
  end

  namespace :shop_admin do
    root 'index#index'
    
    devise_for :shop_users

    scope :profile do
      root 'profile#show', as: :profile
      resource :legal_entity, controller: :legal_entity, only: [:edit, :update]
      resources :stores
      resources :shops do
        resources :shop_delivery_values, except: [:index]
      end
    end

    scope :settings do
      root 'account_settings#edit', as: :settings
      resource :account_settings, only: [:update]
    end

    resources :notifications, only: [:index, :destroy]
    resources :reports, only: [:index]
    
    resources :orders, except: [:destroy] do
      resources :order_items, except: [:index, :show]
      member do
        get :publish
        get :confirm
        get :cancel
        get :courier
      end
    end

    resource :documents, only: [] do
      get :transmission_reception
      get :transmission_return
      get :cancel
      get :agent
    end
  end

  scope :courier_admin do
    devise_for :courier_users
  end

  namespace :gp_core do
    namespace :api do
      namespace :v1 do
        resources :orders
      end
    end
  end
end

app/controllers/shop_admin/account_settings_controller.rb
module ShopAdmin
  class AccountSettingsController < ShopAdmin::ApplicationController
    before_action :set_user

    def edit
    end

    def update
      if @user.update_with_password(user_params)
      else
        render :edit
      end
    end

    private
      def set_user
        @user = current_user
      end

      def user_params
        params.require(:shop_user).permit(:email, :password, :password_confirmation, :current_password)
      end
  end
end

app/controllers/shop_admin/application_controller.rb
module ShopAdmin
  class ApplicationController < ActionController::Base
    before_action :authenticate_shop_admin_shop_user!
    protect_from_forgery with: :exception
    layout 'shop_admin'
    helper ShopAdmin::UsersHelper
    include ShopAdmin::UsersHelper
  end
end

app/controllers/shop_admin/confirmations_controller.rb
class ShopAdmin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop_admin/documents_controller.rb
module ShopAdmin
  class DocumentsController < ShopAdmin::ApplicationController
    def transmission_reception
    end

    def transmission_return
    end

    def agent
    end

    def cancel
    end
  end
end

app/controllers/shop_admin/index_controller.rb
module ShopAdmin
  class IndexController < ShopAdmin::ApplicationController
    def index
    	redirect_to shop_admin_profile_path if user_signed_in?
    end
  end
end

app/controllers/shop_admin/legal_entity_controller.rb
module ShopAdmin
  class LegalEntityController < ShopAdmin::ApplicationController
    before_action :set_legal_entity, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      if @legal_entity.update(legal_entity_params)
        redirect_to edit_shop_admin_legal_entity_path, notice: 'Legal entity was successfully updated.'
      else
        render :edit
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_legal_entity
        @legal_entity = current_user.legal_entity
      end

      def legal_entity_params 
        params.require(:legal_entity).permit(:title, :legal_address, :physical_address,
          :ogrn, :inn, :kpp, :okved, :okpo, :bik, :bank_name,
          :correspondent_account,:checking_account, :general_manager,
          :general_accountant, :contact_phone, :contact_email)
      end
  end
end

app/controllers/shop_admin/notifications_controller.rb
module ShopAdmin
  class NotificationsController < ShopAdmin::ApplicationController
    before_action :set_notification, only: [:destroy]

    def index
      @notifications = current_user.notifications.all
    end

    def destroy
      @notification.destroy
      redirect_to shop_admin_notifications_url, notice: 'Notification was successfully destroyed.'
    end

    private
      
      def set_notification
        @notification = current_user.notifications.find(params[:id])
      end
  end
end

app/controllers/shop_admin/omniauth_callbacks_controller.rb
class ShopAdmin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop_admin/order_items_controller.rb
module ShopAdmin
  class OrderItemsController < ShopAdmin::ApplicationController
    before_action :set_order
    before_action :set_order_item,
        only: [:show, :edit, :update, :destroy]

    # GET /order_items/new
    def new
      @order_item = OrderItem.new
    end

    # GET /order_items/1/edit
    def edit
    end

    # POST /order_items
    def create
      @order_item = @order.order_items.build(order_item_params)

      if @order_item.save
        redirect_to [:shop_admin, @order], notice: 'Order item was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /order_items/1
    def update
      if @order_item.update(order_item_params)
        redirect_to [:shop_admin, @order], notice: 'Order item was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /order_items/1
    def destroy
      @order_item.destroy
      redirect_to shop_admin_order_url(@order), notice: 'Order item was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = current_user.orders.find(params[:order_id])
      end

      def set_order_item
        @order_item = @order.order_items.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def order_item_params
        params.require(:order_item).permit(:shop_good_id,
          :size, :price, :estimated_price, :count)
      end
  end
end

app/controllers/shop_admin/orders_controller.rb
module ShopAdmin
  class OrdersController < ShopAdmin::ApplicationController
    before_action :set_order, except: [:index, :new, :create]

    # GET /orders
    def index
      @q = current_user.orders.search(params[:q])
      @orders = @q.result
    end

    # GET /orders/1
    def show
    end

    # GET /orders/new
    def new
      @order = Order.new
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    def create
      @order = current_user.orders.build(order_params)
      if @order.save
        redirect_to [:shop_admin, @order], notice: 'Order was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /orders/1
    def update
      if @order.update(order_params)
        redirect_to [:shop_admin, @order], notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    def publish
      if OrderStatusManager.new(@order).publish
        flash[:notice] = 'Order was successfully published.'
      end
      redirect_to [:shop_admin, @order]
    end

    def confirm
      if OrderStatusManager.new(@order).confirm
        flash[:notice] = 'Order was successfully confirmed.'
      end
      redirect_to [:shop_admin, @order]
    end

    def cancel
      if OrderStatusManager.new(@order).cancel_by_shop
        flash[:notice] = 'Order was successfully canceled.'
      end
      redirect_to [:shop_admin, @order]
    end

    def courier
      if OrderStatusManager.new(@order).transfer_to_courier
        flash[:notice] = 'Order was successfully transfered to courier.'
      end
      redirect_to [:shop_admin, @order]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = current_user.orders.find(params[:id])
      end

      def order_params
        store = current_user.stores.find(params[:order][:store_id])

        params.require(:order).permit(:shop_user_id, :shop_title,
          :shop_order_id, :shop_price, :store_id, :store_address, :store_address_info,
          :courier_order_id,:courier_id, :courier_order_id, :status_id,
          :customer_name, :customer_phone, :customer_second_phone, :customer_email,
          :delivery_address, :goods_estimated_price, :goods_price, :intercom_code, :payment_type, :comments).merge({
            shop_user_id: current_user.id,
            shop_id: store.shop.id,
            shop_title: store.shop.title,
            shop_price: store.shop.calculate_compensation(params[:order][:goods_price]),
            store_address: store.address,
            store_address_info: store.address_info
          })
      end

      def search_params
        params.require(:order).permit(:shop_id, :shop_order_id, :created_at, :status_id, :store_id)
      end
  end
end

app/controllers/shop_admin/passwords_controller.rb
class ShopAdmin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop_admin/profile_controller.rb
module ShopAdmin
  class ProfileController < ShopAdmin::ApplicationController
    def show
    end
  end
end

app/controllers/shop_admin/registrations_controller.rb
class ShopAdmin::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop_admin/reports_controller.rb
module ShopAdmin
  class ReportsController < ShopAdmin::ApplicationController
    def index
    end
  end
end

app/controllers/shop_admin/sessions_controller.rb
class ShopAdmin::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/shop_admin/shop_delivery_values_controller.rb
module ShopAdmin
  class ShopDeliveryValuesController < ShopAdmin::ApplicationController
    before_action :set_shop
    before_action :set_shop_delivery_value, except: [:new, :create]
    
    # GET /shop_delivery_values/1
    def show
    end

    # GET /shop_delivery_values/new
    def new
      @shop_delivery_value = ShopDeliveryValue.new
    end

    # GET /shop_delivery_values/1/edit
    def edit
    end

    # POST /shop_delivery_values
    def create
      @shop_delivery_value = @shop.shop_delivery_values.build(shop_delivery_value_params)

      if @shop_delivery_value.save
        redirect_to [:shop_admin, @shop], notice: 'Shop delivery value was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /shop_delivery_values/1
    def update
      if @shop_delivery_value.update(shop_delivery_value_params)
        redirect_to [:shop_admin, @shop], notice: 'Shop delivery value was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /shop_delivery_values/1
    def destroy
      @shop_delivery_value.destroy
      redirect_to shop_admin_shop_url(@shop), notice: 'Shop delivery value was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_shop_delivery_value
        @shop_delivery_value = @shop.shop_delivery_values.find(params[:id])
      end

      def set_shop
        @shop = current_user.shops.find(params[:shop_id])
      end

      # Only allow a trusted parameter "white list" through.
      def shop_delivery_value_params
        params.require(:shop_delivery_value).permit(:less_than, :greater_than,
            :equal_to, :shop_delivery_value)
      end
  end
end

app/controllers/shop_admin/shops_controller.rb
module ShopAdmin
  class ShopsController < ShopAdmin::ApplicationController
    before_action :set_shop, only: [:show, :edit, :update, :destroy]

    # GET /shops
    def index
      @shops = current_user.shops.all
    end

    # GET /shops/1
    def show
    end

    # GET /shops/new
    def new
      @shop = Shop.new
    end

    # GET /shops/1/edit
    def edit
    end

    # POST /shops
    def create
      @shop = current_user.shops.build(shop_params)
      if @shop.save
        redirect_to [:shop_admin, @shop], notice: 'Shop was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /shops/1
    def update
      if @shop.update(shop_params)
        redirect_to [:shop_admin, @shop], notice: 'Shop was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /shops/1
    def destroy
      @shop.destroy
      redirect_to shop_admin_shops_url, notice: 'Shop was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_shop
        @shop = current_user.shops.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def shop_params
        params.require(:shop).permit(:title, :contact_name,
          :address, :phone, :email)
      end
  end
end

app/controllers/shop_admin/unlocks_controller.rb
class ShopAdmin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/shop_admin/users_helper.rb
module ShopAdmin
  module UsersHelper
    def current_user
      current_shop_admin_shop_user
    end

    def user_signed_in?
      shop_admin_shop_user_signed_in?
    end
  end
end

app/views/shop_admin/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shop_admin/shared/_profile_navigation.html.slim
= content_for :navigation do
  .navbar.navbar-default.navbar-static-top.profile-navigation
      .container-fluid
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav.pull-left
            = active_link_to "Общая информация", shop_admin_profile_path, wrap_tag: :li, active: :exclusive
            = active_link_to "Реквизиты", edit_shop_admin_legal_entity_path, wrap_tag: :li

            li class=active_link_to_class(shop_admin_shops_path)
              a href=shop_admin_shops_path
                span= "Магазины"
                '
                span.badge= current_user.shops.count

            li class=active_link_to_class(shop_admin_stores_path)
              a href=shop_admin_stores_path
                span= "Склады"
                '
                span.badge= current_user.shops.count

            = active_link_to "Дополнительно", '#', wrap_tag: :li

app/views/shop_admin/shared/_settings_navigation.html.slim
= content_for :navigation do
  .navbar.navbar-default.navbar-static-top.profile-navigation
      .container-fluid
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav.pull-left
            = active_link_to "Аккаунт", shop_admin_account_settings_path, wrap_tag: :li, active: :exclusive

            = active_link_to "Магазин", '#', wrap_tag: :li

            = active_link_to "Виджет", '#', wrap_tag: :li

app/views/shop_admin/shared/_shops.html.slim
table class="table table-striped"
  thead
    tr
      th= "Название"
      th= "Контактное лицо"
      th= "Адрес"
      th= "Номер ответственного лица"
      th= "E-mail ответственного лица"
      - if editable
        th
  tbody
    - shops.each do |shop|
      tr data-shop-id=shop.id
        td= link_to shop.title, shop_admin_shop_path(shop)
        td= shop.contact_name
        td= shop.address
        td= shop.phone
        td= shop.email
        - if editable
          td
            = link_to 'Редактировать', edit_shop_admin_shop_path(shop), :class => 'btn btn-default btn-xs'
            '
            = link_to 'Удалить', shop_admin_shop_path(shop), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/shop_admin/shared/_stores.html.slim
table class="table table-striped"
  thead
    tr
      th= "Название"
      th= "Контактное лицо"
      th= "Адрес"
      th= "Номер телефона"
      - if editable
        th
  tbody
    - stores.each do |store|
      tr data-store-id=store.id
        td= link_to store.title, shop_admin_store_path(store)
        td= store.contact_name
        td= store.address
        td= store.phone
        - if editable
          td
            = link_to 'Редактировать', edit_shop_admin_store_path(store), :class => 'btn btn-default btn-xs'
            '
            = link_to 'Удалить', shop_admin_store_path(store), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'