config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  namespace :courier_admin do
    root 'index#index'
    resources :legal_entities
    resources :courier_services
    resources :couriers
    resources :orders do
      member do
        get :cancel
        get :courier
      end
    end
  end

  namespace :shop_admin do
    root 'index#index'
    
    devise_for :shop_users

    scope :profile do
      root 'profile#show', as: :profile
      resource :legal_entity, controller: :legal_entity, only: [:edit, :update]
      resources :stores
      resources :shops do
        resources :shop_delivery_values, except: [:index]
      end
    end

    scope :settings do
      root 'account_settings#edit', as: :settings
      resource :account_settings, only: [:update]
    end

    resources :notifications, only: [:index, :destroy]
    resources :reports, only: [:index]
    
    resources :orders, except: [:destroy] do
      resources :order_items, except: [:index, :show]
      member do
        get :publish
        get :confirm
        get :cancel
        get :courier
      end
    end

    resource :documents, only: [] do
      get :transmission_reception
      get :transmission_return
      get :cancel
      get :agent
    end
  end

  scope :courier_admin do
    devise_for :courier_users
  end

  namespace :gp_core do
    namespace :api do
      namespace :v1 do
        resources :orders
      end
    end
  end
end

app/controllers/courier_admin/orders_controller.rb
module CourierAdmin
  class OrdersController < CourierAdmin::ApplicationController
    before_action :set_order, except: [:index, :new, :create]

    # GET /orders
    def index
      @orders = current_courier_user.orders.all
    end

    # GET /orders/1
    def show
    end

    # GET /orders/new
    def new
      @order = Order.new
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    def create
      @order = current_courier_user.orders.build(order_params)

      if @order.save
        redirect_to [:courier_admin, @order], notice: 'Order was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /orders/1
    def update
      if @order.update(order_params)
        redirect_to [:courier_admin, @order], notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /orders/1
    def destroy
      @order.destroy
      redirect_to courier_admin_orders_url, notice: 'Order was successfully destroyed.'
    end

    def courier
      if OrderStatusManager.new(@order).transfer_to_courier
        flash[:notice] = 'Order was successfully transfered to courier.'
      end
      redirect_to [:courier_admin, @order]
    end

    def cancel
      if OrderStatusManager.new(@order).cancel_by_courier
        flash[:notice] = 'Order was successfully canceled.'
      end
      redirect_to [:courier_admin, @order]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = Order.where(id: params[:id],
          courier_user_id: current_courier_user.id).first
      end

      def order_params
        
        params.require(:order).permit(:status_id, :courier_user_id, :shop_id,
          :shop_order_id, :store_id, :store_address, :courier_order_id,
          :courier_id, :courier_order_id, :status_id, :client_name, :client_phone,
          :client_second_phone, :client_email, :address, :floor, :intercom_code,
          :goods_title, :goods_count, :goods_weight, :goods_estimated_value,
          :goods_value, :delivery_value, :goods_estimated_value, :payment_type,
          :comments)
      end
  end
end

app/controllers/gp_core/api/v1/orders_controller.rb
module GpCore
  module Api
    module V1
      class OrdersController < ApiApplicationController
        def create
          order = Order.create(published_order_params)
          respond_with(order)
        end

        private
          def published_order_params
            params[:order].merge!(status_id: 0,
              delivery_value: 500,
              goods_estimated_value: 1000)
            
            params.require(:order).permit(:shop_user_id, :shop_id, :shop_order_id, :store_id,
              :store_address, :courier_order_id, :courier_id, :courier_order_id,
              :status_id, :client_name, :client_phone, :client_second_phone,
              :client_email, :address, :floor, :intercom_code, :goods_title,
              :goods_count, :goods_weight, :goods_estimated_value, :goods_value,
              :payment_type, :comments)
          end
      end
    end
  end
end

app/controllers/shop_admin/account_settings_controller.rb
module ShopAdmin
  class AccountSettingsController < ShopAdmin::ApplicationController
    before_action :set_user

    def edit
    end

    def update
      if @user.update_with_password(user_params)
      else
        render :edit
      end
    end

    private
      def set_user
        @user = current_user
      end

      def user_params
        params.require(:shop_user).permit(:email, :password, :password_confirmation, :current_password)
      end
  end
end

app/controllers/shop_admin/application_controller.rb
module ShopAdmin
  class ApplicationController < ActionController::Base
    before_action :authenticate_shop_admin_shop_user!
    protect_from_forgery with: :exception
    layout 'shop_admin'
    helper ShopAdmin::UsersHelper
    include ShopAdmin::UsersHelper
  end
end

app/controllers/shop_admin/confirmations_controller.rb
class ShopAdmin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop_admin/documents_controller.rb
module ShopAdmin
  class DocumentsController < ShopAdmin::ApplicationController
    def transmission_reception
    end

    def transmission_return
    end

    def agent
    end

    def cancel
    end
  end
end

app/controllers/shop_admin/index_controller.rb
module ShopAdmin
  class IndexController < ShopAdmin::ApplicationController
    def index
    	redirect_to shop_admin_profile_path if user_signed_in?
    end
  end
end

app/controllers/shop_admin/legal_entity_controller.rb
module ShopAdmin
  class LegalEntityController < ShopAdmin::ApplicationController
    before_action :set_legal_entity, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      if @legal_entity.update(legal_entity_params)
        redirect_to edit_shop_admin_legal_entity_path, notice: 'Legal entity was successfully updated.'
      else
        render :edit
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_legal_entity
        @legal_entity = current_user.legal_entity
      end

      def legal_entity_params 
        params.require(:legal_entity).permit(:title, :legal_address, :physical_address,
          :ogrn, :inn, :kpp, :okved, :okpo, :bik, :bank_name,
          :correspondent_account,:checking_account, :general_manager,
          :general_accountant, :contact_phone, :contact_email)
      end
  end
end

app/controllers/shop_admin/notifications_controller.rb
module ShopAdmin
  class NotificationsController < ShopAdmin::ApplicationController
    before_action :set_notification, only: [:destroy]

    def index
      @notifications = current_user.notifications.all
    end

    def destroy
      @notification.destroy
      redirect_to shop_admin_notifications_url, notice: 'Notification was successfully destroyed.'
    end

    private
      
      def set_notification
        @notification = current_user.notifications.find(params[:id])
      end
  end
end

app/controllers/shop_admin/omniauth_callbacks_controller.rb
class ShopAdmin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop_admin/order_items_controller.rb
module ShopAdmin
  class OrderItemsController < ShopAdmin::ApplicationController
    before_action :set_order
    before_action :set_order_item,
        only: [:show, :edit, :update, :destroy]

    # GET /order_items/new
    def new
      @order_item = OrderItem.new
    end

    # GET /order_items/1/edit
    def edit
    end

    # POST /order_items
    def create
      @order_item = @order.order_items.build(order_item_params)

      if @order_item.save
        redirect_to [:shop_admin, @order], notice: 'Order item was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /order_items/1
    def update
      if @order_item.update(order_item_params)
        redirect_to [:shop_admin, @order], notice: 'Order item was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /order_items/1
    def destroy
      @order_item.destroy
      redirect_to shop_admin_order_url(@order), notice: 'Order item was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = current_user.orders.find(params[:order_id])
      end

      def set_order_item
        @order_item = @order.order_items.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def order_item_params
        params.require(:order_item).permit(:shop_good_id,
          :size, :price, :estimated_price, :count)
      end
  end
end

app/controllers/shop_admin/orders_controller.rb
module ShopAdmin
  class OrdersController < ShopAdmin::ApplicationController
    before_action :set_order, except: [:index, :new, :create]

    # GET /orders
    def index
      @q = current_user.orders.search(params[:q])
      @orders = @q.result
    end

    # GET /orders/1
    def show
    end

    # GET /orders/new
    def new
      @order = Order.new
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    def create
      @order = current_user.orders.build(order_params)
      if @order.save
        redirect_to [:shop_admin, @order], notice: 'Order was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /orders/1
    def update
      if @order.update(order_params)
        redirect_to [:shop_admin, @order], notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end

    def publish
      if OrderStatusManager.new(@order).publish
        flash[:notice] = 'Order was successfully published.'
      end
      redirect_to [:shop_admin, @order]
    end

    def confirm
      if OrderStatusManager.new(@order).confirm
        flash[:notice] = 'Order was successfully confirmed.'
      end
      redirect_to [:shop_admin, @order]
    end

    def cancel
      if OrderStatusManager.new(@order).cancel_by_shop
        flash[:notice] = 'Order was successfully canceled.'
      end
      redirect_to [:shop_admin, @order]
    end

    def courier
      if OrderStatusManager.new(@order).transfer_to_courier
        flash[:notice] = 'Order was successfully transfered to courier.'
      end
      redirect_to [:shop_admin, @order]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_order
        @order = current_user.orders.find(params[:id])
      end

      def order_params
        store = current_user.stores.find(params[:order][:store_id])

        params.require(:order).permit(:shop_user_id, :shop_title,
          :shop_order_id, :shop_price, :store_id, :store_address, :store_address_info,
          :courier_order_id,:courier_id, :courier_order_id, :status_id,
          :customer_name, :customer_phone, :customer_second_phone, :customer_email,
          :delivery_address, :goods_estimated_price, :goods_price, :intercom_code, :payment_type, :comments).merge({
            shop_user_id: current_user.id,
            shop_id: store.shop.id,
            shop_title: store.shop.title,
            shop_price: store.shop.calculate_compensation(params[:order][:goods_price]),
            store_address: store.address,
            store_address_info: store.address_info
          })
      end

      def search_params
        params.require(:order).permit(:shop_id, :shop_order_id, :created_at, :status_id, :store_id)
      end
  end
end

app/controllers/shop_admin/passwords_controller.rb
class ShopAdmin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop_admin/profile_controller.rb
module ShopAdmin
  class ProfileController < ShopAdmin::ApplicationController
    def show
    end
  end
end

app/controllers/shop_admin/registrations_controller.rb
class ShopAdmin::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop_admin/reports_controller.rb
module ShopAdmin
  class ReportsController < ShopAdmin::ApplicationController
    def index
    end
  end
end

app/controllers/shop_admin/sessions_controller.rb
class ShopAdmin::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/shop_admin/shops_controller.rb
module ShopAdmin
  class ShopsController < ShopAdmin::ApplicationController
    before_action :set_shop, only: [:show, :edit, :update, :destroy]

    # GET /shops
    def index
      @shops = current_user.shops.all
    end

    # GET /shops/1
    def show
    end

    # GET /shops/new
    def new
      @shop = Shop.new
    end

    # GET /shops/1/edit
    def edit
    end

    # POST /shops
    def create
      @shop = current_user.shops.build(shop_params)
      if @shop.save
        redirect_to [:shop_admin, @shop], notice: 'Shop was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /shops/1
    def update
      if @shop.update(shop_params)
        redirect_to [:shop_admin, @shop], notice: 'Shop was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /shops/1
    def destroy
      @shop.destroy
      redirect_to shop_admin_shops_url, notice: 'Shop was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_shop
        @shop = current_user.shops.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def shop_params
        params.require(:shop).permit(:title, :contact_name,
          :address, :phone, :email)
      end
  end
end

app/views/shop_admin/orders/_filters_form.html.slim
.content-block
  = search_form_for [:shop_admin, q] do |f|
    .input
      = f.label :shop_order_id
      ''
      = f.search_field :shop_order_id_eq
    .input
      = f.label :store_id
      '
      = f.select :store_id_eq, current_user.stores.map { |s| [s.title_with_shop, s.id] }, include_blank: true
    .input
      = f.label :status_id
      '
      = f.select :status_id_eq, Order.new.status_options_list, include_blank: true
    .input
      = f.label :created_at_gteq
      '
      = f.date_select :created_at_gteq, include_blank: true, order: [:day, :month, :year]
    .input
      = f.label :created_at_lteq
      '
      = f.date_select :created_at_lteq, include_blank: true, order: [:day, :month, :year]

    = f.submit value: 'Найти'

app/views/shop_admin/orders/_form.html.slim
= simple_form_for [:shop_admin, @order], :html => { :class => "form-horizontal" } do |f|
  = f.input :store_id, :collection => current_user.stores,:label_method => :title_with_shop, :value_method => :id, :include_blank => false
  = error_span(@order[:store_id])
  = f.input :shop_order_id
  = error_span(@order[:shop_order_id])
  = f.input :customer_name
  = error_span(@order[:customer_name])
  = f.input :customer_phone
  = error_span(@order[:customer_phone])
  = f.input :customer_second_phone
  = error_span(@order[:customer_second_phone])
  = f.input :customer_email
  = error_span(@order[:customer_email])
  = f.input :delivery_address
  = error_span(@order[:delivery_address])
  = f.input :floor
  = error_span(@order[:floor])
  = f.input :intercom_code
  = error_span(@order[:intercom_code])
  = f.input :goods_price
  = error_span(@order[:goods_price])
  = f.input :goods_estimated_price
  = error_span(@order[:goods_estimated_price])
  = f.input :payment_type, :collection => @order.payment_types_options_list, :include_blank => false
  = error_span(@order[:payment_type])
  = f.input :comments
  = error_span(@order[:comments])
  = f.button :submit, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), shop_admin_orders_path, :class => 'btn btn-default'

app/views/shop_admin/orders/_order_items.html.slim
.page-header
  = link_to 'Добавить товар', new_shop_admin_order_order_item_path(order), :class => 'btn btn-success pull-right'
  h1= "Корзина заказа"

table class="table table-striped"
  thead
    tr
      th= "Номер товара в ИМ"
      th= "Размер"
      th= "Стоимость"
      th= "Оценочная стоимость"
      th= "Количество"
      th
      th

  tbody
    - order.order_items.each do |order_item|
      tr data-order-item-id=order_item.id
        td = order_item.shop_good_id
        td = order_item.size
        td = order_item.price
        td = order_item.estimated_price
        td = order_item.count
        td = link_to 'Редактировать', edit_shop_admin_order_order_item_path(order, order_item), :class => 'btn btn-default btn-xs'
        td = link_to 'Удалить', [:shop_admin, order, order_item], data: {:confirm => 'Are you sure?'}, :method => :delete, :class => 'btn btn-xs btn-danger'

app/views/shop_admin/orders/edit.html.slim
.container
  .content-block
    - model_class = Order
    .page-header
      h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
    = render :partial => "form"

app/views/shop_admin/orders/index.html.slim
.content-block-wide
  div class="page-header"
    = link_to "Добавить", new_shop_admin_order_path, :class => 'btn btn-success pull-right'
    h1="Заказы"

  = render :partial => "filters_form", locals: { q: @q }

  table class="table table-striped"
    thead
      tr
        th= "Номер заказа в GP"
        th= "Название магазина"
        th= "Статус"
        th= "Адрес склада"
        th= "Дата подачи заявки"
        th=t '.actions', :default => t("helpers.actions")
    tbody
      - @orders.each do |order|
        tr data-order-id=order.id
          td= order.id
          td= order.shop_title
          td= order.status_name
          td= order.store_address
          td=l order.created_at
          td
            = link_to "Перейти", shop_admin_order_path(order), :class => 'btn btn-default btn-xs'
            '
            = link_to "Редактировать", edit_shop_admin_order_path(order), :class => 'btn btn-default btn-xs'
            '

app/views/shop_admin/orders/new.html.slim
.container
  .content-block
    - model_class = Order
    div class="page-header"
      h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
    = render :partial => "form"

app/views/shop_admin/orders/show.html.slim
.container
  .content-block
    - model_class = Order
    div class="page-header"
      h1= "Заказ \##{@order.id}"
    p
      strong= model_class.human_attribute_name(:shop_order_id) + ':'
      br
      = @order.shop_order_id
    p
      strong= model_class.human_attribute_name(:shop_title) + ':'
      br
      = @order.shop_title
    p
      strong= model_class.human_attribute_name(:store_address) + ':'
      br
      = @order.store_address
    p
      strong= model_class.human_attribute_name(:status_id) + ':'
      br
      = @order.status_name
    p
      strong= model_class.human_attribute_name(:customer_name) + ':'
      br
      = @order.customer_name
    p
      strong= model_class.human_attribute_name(:customer_phone) + ':'
      br
      = @order.customer_phone
    p
      strong= model_class.human_attribute_name(:customer_second_phone) + ':'
      br
      = @order.customer_second_phone
    p
      strong= model_class.human_attribute_name(:customer_email) + ':'
      br
      = @order.customer_email
    p
      strong= model_class.human_attribute_name(:delivery_address) + ':'
      br
      = @order.delivery_address
    p
      strong= model_class.human_attribute_name(:floor) + ':'
      br
      = @order.floor
    p
      strong= model_class.human_attribute_name(:intercom_code) + ':'
      br
      = @order.intercom_code
    p
      strong= model_class.human_attribute_name(:goods_estimated_price) + ':'
      br
      = @order.goods_estimated_price
    p
      strong= model_class.human_attribute_name(:goods_price) + ':'
      br
      = @order.goods_price
    p
      strong= model_class.human_attribute_name(:delivery_price) + ':'
      br
      = @order.delivery_price
    p
      strong= model_class.human_attribute_name(:payment_type) + ':'
      br
      = @order.payment_type_name
    p
      strong= model_class.human_attribute_name(:comments) + ':'
      br
      = @order.comments

    - if @order.has_status?(:unpublished) && @order.order_items.count > 0
      = link_to t('order.publish'), publish_shop_admin_order_path(@order), :class => 'btn btn-default'

    - if @order.has_status?(:published)
      = link_to t('order.confirm'), confirm_shop_admin_order_path(@order), :class => 'btn btn-default'

    - if @order.has_status?(:published) ||  @order.has_status?(:confirmed) || @order.has_status?(:assigned) 
      = link_to t('order.cancel'), cancel_shop_admin_order_path(@order), :class => 'btn btn-default'

    - if @order.has_status?(:assigned)
      = link_to t('order.courier'), courier_shop_admin_order_path(@order), :class => 'btn btn-default'

    = link_to 'Назад', shop_admin_orders_path, :class => 'btn btn-default'
    '
    = link_to 'Редактировать', edit_shop_admin_order_path(@order), :class => 'btn btn-default'
    '
    
  .content-block
    = render partial: 'order_items', locals: { order: @order }